"""
Utilities for formatting TriageOutput objects for terminal display and Markdown export.
"""

from typing import List
from src.schemas import TriageOutput


def format_terminal_output(results: List[TriageOutput]) -> str:
    """Format triage results for clean, readable terminal viewing."""
    lines = []
    lines.append("=" * 80)
    lines.append("                    RESEARCH PAPER TRIAGE AGENT REPORT                  ")
    lines.append("=" * 80)
    lines.append("")

    for idx, res in enumerate(results, 1):
        lines.append(f"[{idx}] {res.title}")
        lines.append("-" * 80)
        lines.append(f"  * Recommendation : {res.decision.upper()}")
        lines.append(f"  * Paper Type     : {res.paper_type.capitalize()}")
        lines.append(f"  * Difficulty     : {res.difficulty.capitalize()}")
        lines.append(f"  * Topic Tags     : {', '.join(res.topic_tags)}")
        lines.append(f"  * Summary        : {res.summary}")
        lines.append(f"  * Reason         : {res.reason}")
        if res.source_url:
            lines.append(f"  * Source URL     : {res.source_url}")

        lines.append("  * Prerequisites  :")
        for prereq in res.prerequisites:
            lines.append(f"      - {prereq}")

        lines.append("  * Reading Path   :")
        for step in res.reading_path:
            lines.append(f"      {step}")
        lines.append("")

    lines.append("=" * 80)
    return "\n".join(lines)


def format_markdown_output(results: List[TriageOutput]) -> str:
    """Format triage results into structured Markdown."""
    lines = []
    lines.append("# Research Paper Triage Agent - Report")
    lines.append("")
    lines.append(
        "This report was automatically generated by the Research Paper Triage Agent MVP."
    )
    lines.append("")

    for idx, res in enumerate(results, 1):
        lines.append(f"## {idx}. {res.title}")
        lines.append("")
        lines.append(f"- **Recommendation**: `{res.decision}`")
        lines.append(f"- **Paper Type**: `{res.paper_type}`")
        lines.append(f"- **Difficulty Level**: `{res.difficulty}`")
        lines.append(f"- **Topics**: {', '.join([f'`{t}`' for t in res.topic_tags])}")
        if res.source_url:
            lines.append(f"- **URL**: [{res.source_url}]({res.source_url})")
        lines.append("")
        lines.append("### Summary")
        lines.append(res.summary)
        lines.append("")
        lines.append("### Recommendation Rationale")
        lines.append(res.reason)
        lines.append("")
        lines.append("### Recommended Prerequisites")
        for prereq in res.prerequisites:
            lines.append(f"- {prereq}")
        lines.append("")
        lines.append("### Suggested Reading Path")
        for step in res.reading_path:
            lines.append(f"- {step}")
        lines.append("")
        lines.append("---")
        lines.append("")

    return "\n".join(lines)
